execute: 
  cache: true
  message: false
  warning: false

project:
  type: website
  execute-dir: file
  output-dir: ../docs
  render:
    - index.qmd
    - geo-01-quality.qmd
    #- geo-02-differential.qmd

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    code-fold: show
    standalone: true
    embed-resources: true
    
website:
  title: TLS
  navbar:
    search: false
    left:
      - text: GeoMx
        menu:
          - file: geo-01-quality.qmd
          #- file: geo-02-differential.qmd
      # - id: visium
      #   title: Visium
      #   contents:
      #     - vis-01-quality.qmd
      # - id: mapping
      #   title: Mapping
      #   contents:
      #     - file: map-01-exploratory.qmd





